name: Release DevOps with Docker

on:
  push:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ vermashiva12}}
        password: ${{ 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 }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: shivanshu1verma/node:latest